### ISSUE TITLE
Crash when trying to capture QR code

### ISSUE THREAD

**Issue by flyingOwl** [TheLastProject/Catima#147]
Device:
- Lenovo A2016a40
- Android 6.0
- rooted
- Catima 1.8 from F-Droid

Steps to reproduce:
- Freshly install app
- Click "+" to add a card
- Point camera preview to qrcode

Once the qrcode seems to be recognized, the app crashes. Preview works fine.

Log taken via adb logcat
```
02-12 11:49:28.325  8487  8537 E AndroidRuntime: FATAL EXCEPTION: DecoderThread
02-12 11:49:28.325  8487  8537 E AndroidRuntime: Process: me.hackerchick.catima, PID: 8487
02-12 11:49:28.325  8487  8537 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:624)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:75)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:49)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:146)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:207)
02-12 11:49:28.325  8487  8537 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

Edit: It might be related to https://github.com/zxing/zxing/issues/1170

**Comment by TheLastProject** [comment]
Your research was 100% correct. I've fixed this in ee7f5c049802e4b966405e2c474383b3aa8058d5. I'll build and release v1.8.1 later today. Thank you for the report!
