### ISSUE TITLE
java.lang.IllegalStateException: Could not execute method for android:onClick

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#148]
Caught by Google Play Console Pre-launch Report. Android 5.0-specific bug?

**Device specifications**
Model name: P8 青春版
Manufacturer: Huawei
Android Version (SDK): Android 5.0 (SDK 21)
Locale: it_IT
Screen size: 720 x 1280
Screen density (DPI): 320
RAM (total memory): 2,048 MB
OpenGL ES version: 2.0
ABI: ARM64_V8
CPU: HiSilicon Hi6220

FATAL EXCEPTION: Thread-2021
Process: me.hackerchick.catima, PID: 853
java.lang.IllegalStateException: Could not execute method for android:onClick
	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:414)
	at android.view.View.performClick(View.java:4766)
	at android.view.View$PerformClick.run(View.java:19683)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:11)
	at androidx.test.espresso.base.UiControllerImpl.n(UiControllerImpl.java:6)
	at androidx.test.espresso.base.UiControllerImpl.m(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:6)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:15)
	at androidx.test.espresso.action.Tap.b(Tap.java)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:409)
	... 24 more
Caused by: java.lang.ClassCastException: android.text.SpannableString cannot be cast to java.lang.String
	at protect.card_locker.ManageGroupsActivity.getGroupname(ManageGroupsActivity.java:207)
	at protect.card_locker.ManageGroupsActivity.deleteGroup(ManageGroupsActivity.java:153)
	... 27 more

https://user-images.githubusercontent.com/1885159/107834105-9d354200-6d95-11eb-84e0-ee8d446153d8.mp4

**Comment by TheLastProject** [comment]
This code no longer uses onClick handlers, so this bug can no longer happen.
