### ISSUE TITLE
Import crash on Android 10 (Galaxy S20 5G: detected by Google Play Pre-launch report)

### ISSUE THREAD

**Issue by TheLastProject** [TheLastProject/Catima#627]
It looks like we never asked for storage permission somehow? Or it is something else, but I find it interesting I didn't see a pop-up for that.

https://user-images.githubusercontent.com/1885159/143828652-67365eac-d07b-4ade-9c03-102a7093e969.mp4

```
FATAL EXCEPTION: Thread-8
Process: me.hackerchick.catima, PID: 6440
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.PICK cmp=com.android.stk/.StkMenuActivity } from ProcessRecord{e5598c9 6440:me.hackerchick.catima/u0a285} (pid=6440, uid=10285) not exported from uid 1001
	at android.os.Parcel.createException(Parcel.java:2088)
	at android.os.Parcel.readException(Parcel.java:2056)
	at android.os.Parcel.readException(Parcel.java:2004)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:4311)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1713)
	at android.app.Activity.startActivityForResult(Activity.java:5252)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:239)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at protect.card_locker.ImportExportActivity$1.onClick(ImportExportActivity.java:243)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:5)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
	at androidx.test.espresso.action.Tap.-$$Nest$smsendSingleTap(Unknown Source:0)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1378)
	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:925)
	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:698)
	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1926)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:629)
```

**Comment by TheLastProject** [comment]
Haven't seen this happen in production and it works on my device. So... idk... closing as unconfirmed.
