### ISSUE TITLE
Impossible to create shortcut due to merge #680

### ISSUE THREAD

**Issue by Altonss** [TheLastProject/Catima#689]
This issue has been reported in #669 . Impossible to create shortcut. See log of the master branch when trying to create shortcut on android 5.0.2 device:
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.hackerchick.catima.debug, PID: 23559
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{me.hackerchick.catima.debug/protect.card_locker.CardShortcutConfigure}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.sqlite.SQLiteDatabase android.content.Context.openOrCreateDatabase(java.lang.String, int, android.database.sqlite.SQLiteDatabase$CursorFactory, android.database.DatabaseErrorHandler)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2335)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544)
        at android.app.ActivityThread.access$900(ActivityThread.java:163)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5608)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.sqlite.SQLiteDatabase android.content.Context.openOrCreateDatabase(java.lang.String, int, android.database.sqlite.SQLiteDatabase$CursorFactory, android.database.DatabaseErrorHandler)' on a null object reference
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:274)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
        at protect.card_locker.CardShortcutConfigure.<init>(CardShortcutConfigure.java:21)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.Class.newInstance(Class.java:1656)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1071)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544) 
        at android.app.ActivityThread.access$900(ActivityThread.java:163) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5608) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1397) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1192) 
I/Process: Sending signal. PID: 23559 SIG: 9`

**Comment by TheLastProject** [comment]
Oh actually I can reproduce it on newer Android too, I was testing an old version, oops.

**Comment by Altonss** [comment]
Haha no problem xD
We might also test if this bug is not occuring in other parts of the app, but for the moment that's the only place I found. I didn't found any solution to this issue on the web yet, so I will continue searching :)

**Comment by TheLastProject** [comment]
Should be fixed in d4e388cf5d91f4712d126eeaa73eb60ed9d53c88.
